<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <UserSecretsId>f47b8302-07ba-46e5-afad-e879233d2520</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.10" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="MySql.Data" Version="8.0.29" />
    <PackageReference Include="PDFsharp" Version="6.2.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.15.0" />
    <PackageReference Include="System.Text.Json" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Basic">
      <HintPath>..\0.DLL\Basic.dll</HintPath>
    </Reference>
    <Reference Include="Dapper">
      <HintPath>..\0.DLL\Dapper.dll</HintPath>
    </Reference>
    <Reference Include="MyOffice">
      <HintPath>..\0.DLL\MyOffice.dll</HintPath>
    </Reference>
    <Reference Include="NPOI">
      <HintPath>..\0.DLL\NPOI.dll</HintPath>
    </Reference>
    <Reference Include="NPOI.OOXML">
      <HintPath>..\0.DLL\NPOI.OOXML.dll</HintPath>
    </Reference>
    <Reference Include="NPOI.OpenXml4Net">
      <HintPath>..\0.DLL\NPOI.OpenXml4Net.dll</HintPath>
    </Reference>
    <Reference Include="NPOI.OpenXmlFormats">
      <HintPath>..\0.DLL\NPOI.OpenXmlFormats.dll</HintPath>
    </Reference>
    <Reference Include="PharmaRosterLib">
      <HintPath>..\0.DLL\PharmaRosterLib.dll</HintPath>
    </Reference>
    <Reference Include="SQLUI">
      <HintPath>..\0.DLL\SQLUI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="fonts\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="fonts\NotoSansTC-Black.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\NotoSansTC-Bold.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\NotoSansTC-ExtraBold.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\NotoSansTC-ExtraLight.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\NotoSansTC-Light.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\NotoSansTC-Medium.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\NotoSansTC-Regular.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\NotoSansTC-SemiBold.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\NotoSansTC-Thin.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\NotoSerifCJKtc-Black.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\NotoSerifCJKtc-Bold.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\NotoSerifCJKtc-ExtraLight.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\NotoSerifCJKtc-Light.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\NotoSerifCJKtc-Medium.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\NotoSerifCJKtc-Regular.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fonts\NotoSerifCJKtc-SemiBold.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
